version: '2.1'

services:
  ntp:
    build:
      context: ../..
      dockerfile: docker/release/Dockerfile
      args:
        app_name: ${PROJECT_NAME}
    network_mode: host
    privileged: true
    environment:
      CHRONY_CMDPORT: 323